# update_fastlane

default_platform(:ios)

platform :ios do
   ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
   ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"

  desc "pus podspec to cocoapods repo"
  lane :lane do
    pod_push(path: "TestFramework.podspec", skip_import_validation: true, allow_warnings: true, verbose: true)
  end
end
